theme: jekyll-theme-minimal
title: 'Genome Assembly Workshop 2020'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction and Lectures
  - title: Intro to the Workshop and Core
    url: base/welcome
  - title: Schedule
    url: base/schedule
  - title: Genome Assembly
    url: https://raw.githubusercontent.com/ucdavis-bioinformatics-training/ucdavis-bioinformatics-training.presentations/master/assembly/Genome_assembly_July_2020.pdf
  - title: Introduction to the DNA Tech Core
    url: https://raw.githubusercontent.com/ucdavis-bioinformatics-training/ucdavis-bioinformatics-training.presentations/master/assembly/dnatech_presentation_genome_assembly_2020.pdf

  - heading: Introduction
  - title: Intro to the Workshop and Core
    url: base/welcome
  - title: Schedule
    url: base/schedule

  - heading: Support
  - title: Cheat Sheets
    url: base/cheatSheetIndex
  - title: Software and Links
    url: software_scripts/software
  - title: Scripts
    url: software_scripts/scripts_links

  - heading: Prerequisites
  - title: CLI - Logging in and Transferring Files
    url: prerequisites/cli/logging-in
  - title: CLI - Intro to Command-Line
    url: prerequisites/cli/command-line-intro
  - title: CLI - Advanced Command-Line (extra)
    url: prerequisites/cli/advanced-command-line
  - title: CLI - Running jobs on the Cluster and using modules
    url: prerequisites/cli/cluster
  - title: Conda
    url: prerequisites/cli/conda
  - title: R - Getting Started
    url: prerequisites/intro2R/RStudio
  - title: R - Intro to R
    url: prerequisites/intro2R/Intro2R_fixed
  - title: R - Prepare Data in R (extra)
    url: prerequisites/intro2R/data_in_R_prepare
  - title: R - Data in R (extra)
    url: prerequisites/intro2R/data_in_R_fixed
  - title: More Materials (extra)
    url: https://ucdavis-bioinformatics-training.github.io/2019-Winter-Bioinformatics_Command_Line_and_R_Prerequisites_Workshop/

  - heading: Snakemake
  - title: Introduction
    url: snakemake/snakemake_intro
  - title: Challenge Answers
    url: snakemake/answer

  - heading: K-mers
  - title: K-mers tutorial
    url: kmers/kmers

  - heading: ONT Assembly
  - title: Assembly using ONT - Hands-on
    url: ONT_Assembly/nanopore

  - heading: ETC
  - title: Closing thoughts
    url: base/closing
  - title: Workshop Photos
    url: photos/photos
  - title: Github page
    url: https://github.com/ucdavis-bioinformatics-training/2020-Genome_Assembly_Workshop
  - title: Report Errors
    url: https://github.com/ucdavis-bioinformatics-training/2020-Genome_Assembly_Workshop/issues
  - title: Biocore website
    url: http://bioinformatics.ucdavis.edu
